//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emildko_Anime_List.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emildko_Anime_List.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///		&lt;!--
        ///		 Created by XML Export feature at MyAnimeList.net
        ///		 Version 1.1.0
        ///		--&gt;
        ///		
        ///		&lt;myanimelist&gt;
        ///		
        ///			&lt;myinfo&gt;
        ///				&lt;user_id&gt;4646800&lt;/user_id&gt;
        ///				&lt;user_name&gt;emildko&lt;/user_name&gt;
        ///				&lt;user_export_type&gt;1&lt;/user_export_type&gt;
        ///				&lt;user_total_anime&gt;846&lt;/user_total_anime&gt;
        ///				&lt;user_total_watching&gt;2&lt;/user_total_watching&gt;
        ///				&lt;user_total_completed&gt;841&lt;/user_total_completed&gt;
        ///				&lt;user_total_onhold&gt;2&lt;/user_total_onhold&gt;
        ///				&lt;user_total_dropped&gt;0&lt;/user_total_dropped&gt;
        ///				&lt;use [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AnimeList {
            get {
                return ResourceManager.GetString("AnimeList", resourceCulture);
            }
        }
    }
}
